[package]
name = "reorg-monitor"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
authors = ["Taiko Labs"]
license = "MIT"
repository = "https://github.com/taikoxyz/taiko-mono"

[[bin]]
name = "reorg-monitor"
path = "bin/reorg-monitor/src/main.rs"

[dependencies]
# async runtime + utilities
tokio = { version = "1.45", default-features = false, features = ["full"] }
futures-util = "0.3.0"

# cli
clap = { version = "4", features = ["derive", "env"] }

# observability
prometheus = "0.13"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# web
axum = "0.7"

# ethereum
alloy = { version = "1.0.13", features = ["full"] }

# types
once_cell = "1.19"
dotenvy = "0.15"
eyre = "0.6"
color-eyre = "0.6"
url = { version = "2.5.0", features = ["serde"] }

[lints.clippy]
cast_lossless = "deny"
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_sign_loss = "deny"
needless_return = "deny"
panicking_overflow_checks = "deny"
unwrap_used = "deny"
