[default]
# False positives
extend-ignore-identifiers-re = [
  "QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG",
  "bafybeiegdqpwx3he5dvoxqklspdjekjepjcobfaakyficksratn73qbbyy",
  "TGE",
  "tge",
  "preconf",
  "preconfer",
  "baed",
  "Groth",
  "groth",
  "GROTH"
]

[files]
extend-exclude = [
  "*.png",
  "*.svg",
  "go.mod",
  "CHANGELOG.md",
  "packages/protocol/audit/code4rena-2024-03-taiko-final-report.md",
  "packages/protocol/contracts/layer1/automata-attestation/**",
  "packages/protocol/deployments/**",
  # TODO: fix typos and remove these
  "packages/taiko-client/**",
]
