definitions:
  big.Int:
    type: object
  encoding.TierFee:
    properties:
      fee:
        $ref: "#/definitions/big.Int"
      tier:
        type: integer
    type: object
  server.CreateAssignmentRequestBody:
    properties:
      expiry:
        type: integer
      feeToken:
        type: string
      tierFees:
        items:
          $ref: "#/definitions/encoding.TierFee"
        type: array
      txListHash:
        items:
          type: integer
        type: array
    type: object
  server.ProposeBlockResponse:
    properties:
      maxBlockID:
        type: integer
      maxProposedIn:
        type: integer
      prover:
        type: string
      signedPayload:
        items:
          type: integer
        type: array
    type: object
  server.Status:
    properties:
      maxExpiry:
        type: integer
      minOptimisticTierFee:
        type: integer
      minSgxTierFee:
        type: integer
      prover:
        type: string
    type: object
info:
  contact:
    email: info@taiko.xyz
    name: API Support
    url: https://community.taiko.xyz/
  license:
    name: MIT
    url: https://github.com/taikoxyz/taiko-mono/blob/main/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Taiko Prover Server API
  version: "1.0"
paths:
  /assignment:
    post:
      consumes:
        - application/json
      parameters:
        - description: assignment request body
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/server.CreateAssignmentRequestBody"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/server.ProposeBlockResponse"
        "422":
          description: prover does not have capacity
          schema:
            type: string
      summary: Try to accept a block proof assignment
  /status:
    get:
      consumes:
        - application/json
      operationId: get-status
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/server.Status"
      summary: Get current prover server status
swagger: "2.0"
