definitions:
  big.Int:
    type: object
  preconfserver.BuildTentativeBlocksRequestBody:
    properties:
      transactionsGroups:
        items:
          $ref: '#/definitions/preconfserver.PreconfTransactionsGroup'
        type: array
    type: object
  preconfserver.BuildTentativeBlocksResponseBody:
    properties:
      tentativeHeaders:
        items:
          $ref: '#/definitions/types.Header'
        type: array
    type: object
  preconfserver.PreconfTransactionsGroup:
    properties:
      anchorBlockID:
        description: AnchorV2 parameters
        type: integer
      anchorStateRoot:
        items:
          type: integer
        type: array
      baseFeePerGas:
        type: integer
      blockId:
        type: integer
      groupId:
        type: integer
      groupStatus:
        $ref: '#/definitions/preconfserver.PreconfTxsGroupStatus'
      parentGasUsed:
        type: integer
      prevRandao:
        items:
          type: integer
        type: array
      signature:
        type: string
      suggestedFeeRecipient:
        items:
          type: integer
        type: array
      timestamp:
        description: Block parameters
        type: integer
      transactions:
        items:
          $ref: '#/definitions/types.Transaction'
        type: array
    type: object
  preconfserver.PreconfTxsGroupStatus:
    enum:
    - finalBlockGroup
    - finalPreconfGroup
    type: string
    x-enum-varnames:
    - StatusFinalBlockGroup
    - StatusFinalPreconfGroup
  preconfserver.RemoveTentativeBlocksRequestBody:
    properties:
      newHead:
        type: integer
    type: object
  preconfserver.RemoveTentativeBlocksResponseBody:
    properties:
      currentHead:
        $ref: '#/definitions/types.Header'
    type: object
  types.Header:
    properties:
      baseFeePerGas:
        allOf:
        - $ref: '#/definitions/big.Int'
        description: BaseFee was added by EIP-1559 and is ignored in legacy headers.
      blobGasUsed:
        description: BlobGasUsed was added by EIP-4844 and is ignored in legacy headers.
        type: integer
      difficulty:
        $ref: '#/definitions/big.Int'
      excessBlobGas:
        description: ExcessBlobGas was added by EIP-4844 and is ignored in legacy
          headers.
        type: integer
      extraData:
        items:
          type: integer
        type: array
      gasLimit:
        type: integer
      gasUsed:
        type: integer
      logsBloom:
        items:
          type: integer
        type: array
      miner:
        items:
          type: integer
        type: array
      mixHash:
        items:
          type: integer
        type: array
      nonce:
        items:
          type: integer
        type: array
      number:
        $ref: '#/definitions/big.Int'
      parentBeaconBlockRoot:
        description: ParentBeaconRoot was added by EIP-4788 and is ignored in legacy
          headers.
        items:
          type: integer
        type: array
      parentHash:
        items:
          type: integer
        type: array
      receiptsRoot:
        items:
          type: integer
        type: array
      requestsRoot:
        description: RequestsHash was added by EIP-7685 and is ignored in legacy headers.
        items:
          type: integer
        type: array
      sha3Uncles:
        items:
          type: integer
        type: array
      stateRoot:
        items:
          type: integer
        type: array
      timestamp:
        type: integer
      transactionsRoot:
        items:
          type: integer
        type: array
      withdrawalsRoot:
        description: WithdrawalsHash was added by EIP-4895 and is ignored in legacy
          headers.
        items:
          type: integer
        type: array
    type: object
  types.Transaction:
    type: object
info:
  contact:
    email: info@taiko.xyz
    name: API Support
    url: https://community.taiko.xyz/
  license:
    name: MIT
    url: https://github.com/taikoxyz/taiko-mono/blob/main/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Taiko Preconfirmation Server API
  version: "1.0"
paths:
  /healthz:
    get:
      consumes:
      - application/json
      operationId: health-check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get current server health status
  /tentativeBlocks:
    delete:
      consumes:
      - application/json
      description: |-
        Remove all tentative blocks from the blockchain beyond the specified block height,
        ensuring the latest block ID does not exceed the given height. This method will fail if
        the block with an ID one greater than the specified height is not a tentative block. If the
        specified block height is greater than the latest tentative block ID, the method will succeed
        without modifying the blockchain.
      parameters:
      - description: preconf blocks creation request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/preconfserver.RemoveTentativeBlocksRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/preconfserver.RemoveTentativeBlocksResponseBody'
    post:
      consumes:
      - application/json
      description: |-
        Insert a group of transactions into a tentative block for preconfirmation. If the group is the
        first for a block, a new tentative block will be created. Otherwise, the transactions will
        be appended to the existing tentative block. The API will fail if:
        1) the block is not tentative, 2) any transaction in the group is invalid or a duplicate, 3)
        block-level parameters are invalid or do not match the current tentative blockâ€™s parameters,
        4) the group ID is not exactly 1 greater than the previous one, or 5) the last group of
        the block indicates no further transactions are allowed.
      parameters:
      - description: preconf blocks creation request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/preconfserver.BuildTentativeBlocksRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/preconfserver.BuildTentativeBlocksResponseBody'
swagger: "2.0"
