[workspace]
members = [
    "bin/client",
    "crates/bindings",
    "crates/event-indexer",
    "crates/proposer",
    "crates/protocol",
    "crates/rpc",
]
resolver = "2"

[workspace.package]
version = "2.0.0"
edition = "2024"
rust-version = "1.88"
authors = ["Taiko Labs"]
license = "MIT"
repository = "https://github.com/taikoxyz/taiko-mono"

[workspace.dependencies]
# async
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3.0"
tokio-stream = "0.1"

# cli
clap = { version = "4", features = ["derive", "env"] }

# observability
metrics = "0.24"
metrics-exporter-prometheus = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# web
http-body-util = "0.1"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "http1", "tokio"] }
tower = { version = "0.4", features = ["util"] }

# ethereum
alloy = "1.0.36"
alloy-consensus = { version = "1.0.36", default-features = false, features = [
  "serde",
] }
alloy-contract = { version = "1.0.36", default-features = false }
alloy-eips = { version = "1.0.36", default-features = false }
alloy-json-rpc = { version = "1.0.36", default-features = false }
alloy-network = { version = "1.0.36", default-features = false }
alloy-node-bindings = { version = "1.0.36" }
alloy-primitives = { version = "1.0.36", default-features = false }
alloy-provider = { version = "1.0.36", default-features = false }
alloy-rlp = { version = "0.3.12", default-features = false }
alloy-rpc-client = { version = "1.0.36", default-features = false }
alloy-rpc-types = { version = "1.0.36", default-features = false }
alloy-rpc-types-engine = { version = "1.0.36", default-features = false }
alloy-rpc-types-eth = { version = "1.0.36", default-features = false }
alloy-signer-local = { version = "1.0.36", default-features = false }
alloy-sol-macro = { version = "1.0.36", default-features = false, features = [
  "json",
] }
alloy-sol-types = { version = "1.0.36", default-features = false }
alloy-transport = { version = "1.0.36", default-features = false }
alloy-transport-http = { version = "1.0.36", features = ["hyper", "jwt-auth"] }
event-scanner = "=0.2.0-alpha"

# taiko
alethia-reth = { git = "https://github.com/taikoxyz/alethia-reth", branch = "main" }

# types
anyhow = "1"
dashmap = "6.1.0"
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }
thiserror = { version = "2.0.12", default-features = false }
url = "2.5.4"

# serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
