definitions:
  eventindexer.ChartItem:
    properties:
      date:
        type: string
      value:
        type: string
    type: object
  eventindexer.ChartResponse:
    properties:
      chart:
        items:
          $ref: "#/definitions/eventindexer.ChartItem"
        type: array
    type: object
  eventindexer.Stat:
    properties:
      averageProofReward:
        type: string
      averageProofTime:
        type: string
      feeTokenAddress:
        type: string
      id:
        type: integer
      numBlocksAssigned:
        type: integer
      numProofs:
        type: integer
      statType:
        type: string
    type: object
  eventindexer.UniqueProposersResponse:
    properties:
      address:
        type: string
      count:
        type: integer
    type: object
  eventindexer.UniqueProversResponse:
    properties:
      address:
        type: string
      count:
        type: integer
    type: object
  http.uniqueProposersResp:
    properties:
      proposers:
        items:
          $ref: "#/definitions/eventindexer.UniqueProposersResponse"
        type: array
      uniqueProposers:
        type: integer
    type: object
  http.uniqueProversResp:
    properties:
      provers:
        items:
          $ref: "#/definitions/eventindexer.UniqueProversResponse"
        type: array
      uniqueProvers:
        type: integer
    type: object
  paginate.Page:
    properties:
      error:
        type: boolean
      error_message:
        type: string
      first:
        type: boolean
      items: {}
      last:
        type: boolean
      max_page:
        type: integer
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
      visible:
        type: integer
    type: object
host: eventindexer.katla.taiko.xyz
info:
  contact:
    email: info@taiko.xyz
    name: API Support
    url: https://community.taiko.xyz/
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Taiko Eventindexer API
  version: "1.0"
paths:
  /assignedBlocks:
    get:
      consumes:
        - application/json
      operationId: get-assigned-blocks-by-prover-address
      parameters:
        - description: address to query
          in: query
          name: address
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/paginate.Page"
      summary: Get assigned blocks by prover address
  /chart/chartByTask:
    get:
      consumes:
        - application/json
      operationId: get-charts-by-task
      parameters:
        - description: task to query
          in: query
          name: task
          required: true
          type: string
        - description: start date
          in: query
          name: start
          required: true
          type: string
        - description: end date
          in: query
          name: end
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/eventindexer.ChartResponse"
      summary: Get time series data for displaying charts
  /events:
    get:
      consumes:
        - application/json
      operationId: get-events-by-address-and-event-name
      parameters:
        - description: address to query
          in: query
          name: address
          required: true
          type: string
        - description: event name to query
          in: query
          name: event
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/paginate.Page"
      summary: Get events by address and event name
  /nftsByAddress:
    get:
      consumes:
        - application/json
      operationId: get-nft-balances-by-address-and-chain-id
      parameters:
        - description: address to query
          in: query
          name: address
          required: true
          type: string
        - description: chainID to query
          in: query
          name: chainID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/paginate.Page"
      summary: Get nft balances by address and chain ID
  /stats:
    get:
      consumes:
        - application/json
      operationId: get-stats
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/eventindexer.Stat"
      summary: Get stats
  /uniqueProposers:
    get:
      consumes:
        - application/json
      operationId: get-unique-proposers
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/http.uniqueProposersResp"
      summary: Get unique proposers
  /uniqueProvers:
    get:
      consumes:
        - application/json
      operationId: get-unique-provers
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/http.uniqueProversResp"
      summary: Get unique provers
swagger: "2.0"
