contact_links:
    - name: Community support
      url: https://discord.gg/taikoxyz
      about: This issue tracker is only for feature requests and bug reports. Community support is available on Discord!
