[package]
name = "driver"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
alethia-reth-consensus = { workspace = true }
alethia-reth-evm = { workspace = true }
alethia-reth-primitives = { workspace = true }
alloy = { workspace = true }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
event-scanner = { workspace = true }
flate2 = { workspace = true }
jsonrpsee = { workspace = true }
k256 = { workspace = true }
metrics = { workspace = true }
reth-ipc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

bindings = { path = "../bindings" }
protocol = { path = "../protocol" }
rpc = { path = "../rpc" }

[dev-dependencies]
alloy-rlp = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-transport = { workspace = true }
anyhow = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
preconfirmation-client = { path = "../preconfirmation-client" }
preconfirmation-net = { path = "../../../preconfirmation-p2p/crates/net" }
preconfirmation-types = { path = "../../../preconfirmation-p2p/crates/types" }
proposer = { path = "../proposer" }
rand = { workspace = true }
secp256k1 = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
test-context = { workspace = true }
test-harness = { path = "../test-harness", features = ["preconfirmation"] }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
