[package]
name = "protocol"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[dependencies]
# ethereum
alloy = { workspace = true }
alloy-consensus = { workspace = true }
alloy-contract = { workspace = true }
alloy-eips = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-primitives = { workspace = true, default-features = false }
alloy-provider = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types = { workspace = true }
bindings = { path = "../bindings" }
dashmap = { workspace = true }
event-scanner = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }

# types
anyhow = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# serialization
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
rand = { workspace = true, features = ["std", "std_rng"] }
