services:
  bridge-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridge-ui
    ports:
      - '3001:3000'
    profiles:
      - bridge-ui
    networks:
      - app-network
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    profiles:
      - nginx
    networks:
      - app-network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      com.kurtosistech.custom.logs_enabled: "true"
      com.kurtosistech.custom.custom_network: "devnet"

networks:
  app-network:
    driver: bridge
