[profile.default]
src = "contracts"
out = "out"
test = "test"
script = "script"
gas_price = 10_000_000_000 # 10 Gwei
gas_limit = "18446744073709551615" # u64::MAX
optimizer = true
optimizer_runs = 200
ffi = true
memory_limit = 2_073_741_824
solc_version = "0.8.24"
evm_version = "cancun"
ast = true
remappings = [
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "solady/=node_modules/solady/",
  "forge-std/=node_modules/forge-std/",
  "ds-test/=node_modules/ds-test/src/",
  "p256-verifier/=node_modules/p256-verifier/",
  "murky/=node_modules/murky/src/",
  "solidity-stringutils/=node_modules/solidity-stringutils/",
  "@taiko/blacklist/=node_modules/@taiko/supplementary-contracts/contracts/blacklist/",
  "openzeppelin-foundry-upgrades/=node_modules/openzeppelin-foundry-upgrades/src/",
]

# Do not change the block_gas_limit value, TaikoL2.t.sol depends on it.
# For mainnet_mock tokenomics test we need a huge value to run lots of iterations.
# Use 30M for TaikoL2.t.sol related tests, only use this number with mainnet simulation.
block_gas_limit = 80_000_000

fs_permissions = [
  { access = "read", path = "./out" },
  { access = "read-write", path = "./deployments/" },
  { access = "read", path = "./test" },
  { access = "read", path = "./genesis" },
  { access = "read", path = "./data/" },
]

# 2394: Transient storage warning
# 3860: Contract initcode size is xxx bytes and exceeds 49152 bytes
# 5574: Contract code size is xxx bytes and exceeds 24576 byte
ignored_error_codes = [2394, 3860, 5574]
libs = ["node_modules", "lib"]

[fuzz]
runs = 200

[fmt]
bracket_spacing = false
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
wrap_comments = true
