[package]
name = "rpc"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
# observability
tracing = { workspace = true }

# web
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tower = { workspace = true }

# ethereum
alloy = { workspace = true }
alloy-contract = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true, default-features = false }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types = { workspace = true }
alloy-transport-http = { workspace = true }

# taiko
alethia-reth = { workspace = true }
bindings = { path = "../bindings" }

# types
anyhow = { workspace = true }
thiserror = { workspace = true }

# serialization
serde = { workspace = true }
serde_json = { workspace = true }
