[package]
name = "proposer"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[dependencies]
# async
tokio = { workspace = true }

# observability
metrics = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# ethereum
alloy = { workspace = true }
alloy-eips = { workspace = true }
alloy-hardforks = { workspace = true }
alloy-network = { workspace = true }

# taiko
alethia-reth-consensus = { workspace = true }
bindings = { path = "../bindings" }
protocol = { path = "../protocol" }
rpc = { path = "../rpc" }

# types
anyhow = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

# serialization
serde_json = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
test-context = { workspace = true }
test-harness = { path = "../test-harness" }
