[package]
name = "p2p"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
alloy-primitives = { workspace = true }
crossbeam-skiplist = "0.1.3"
dashmap = { workspace = true }
futures = "0.3"
libp2p = { version = "0.56", default-features = false }
lru = "0.12"
metrics = { workspace = true }
moka = { version = "0.12", features = ["sync"] }
parking_lot = "0.12"
preconfirmation-net = { path = "../../../preconfirmation-p2p/crates/net" }
preconfirmation-types = { path = "../../../preconfirmation-p2p/crates/types" }
serde = { workspace = true, features = ["derive"] }
sha3 = "0.10"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
