[package]
name = "p2p"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
futures = "0.3"
lru = "0.12"
moka = { version = "0.12", features = ["sync"] }
preconfirmation-net = { path = "../../../preconfirmation-p2p/crates/net" }
preconfirmation-types = { path = "../../../preconfirmation-p2p/crates/types" }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
metrics = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
