[package]
name = "preconfirmation-types"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = ["Taiko Labs"]

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
ssz_rs.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest = "1"
