name: Guardians UI CI/CD

on:
  push:
    branches-ignore:
      - release-please-*
    paths:
      - "packages/guardian-prover-health-check-ui/**"
  pull_request:
    paths:
      - "packages/guardian-prover-health-check-ui/**"

jobs:
  build-and-test:
    runs-on: [taiko-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Checks
        uses: ./.github/workflows/guardian-prover-health-check-ui-ci.yml

  # Deployment name follow the pattern: deploy_<appname(guardian-prover-health-check-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_guardian-prover-health-check-ui_hekla_preview:
    if: ${{ github.ref_name != 'main' }}
    runs-on: [taiko-runner]
    needs: build-and-test
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_UI_HEKLA }}
    steps:
      - name: Deploy
        uses: ./.github/workflows/vercel-deploy.yml
        with:
          environment: 'preview'
          flags: ''
          vercel_project_id: ${{ env.VERCEL_PROJECT_ID }}

  deploy_guardian-prover-health-check-ui_devnet_preview:
    if: ${{ github.ref_name != 'main' }}
    runs-on: [taiko-runner]
    needs: build-and-test
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_UI_INTERNAL }}
    steps:
      - name: Deploy
        uses: ./.github/workflows/vercel-deploy.yml
        with:
          environment: 'preview'
          flags: ''
          vercel_project_id: ${{ env.VERCEL_PROJECT_ID }}

  deploy_guardian-prover-health-check-ui_hekla_production:
    if: ${{ github.ref_name == 'main' && contains(github.ref, 'refs/tags/guardian-prover-health-check-ui-') }}
    runs-on: [taiko-runner]
    needs: build-and-test
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_UI_HEKLA }}
    steps:
      - name: Deploy
        uses: ./.github/workflows/vercel-deploy.yml
        with:
          environment: 'production'
          flags: '--prod'
          vercel_project_id: ${{ env.VERCEL_PROJECT_ID }}
