name: Guardians UI CI/CD

on:
  push:
    branches-ignore:
      - release-please-*
    paths:
      - "packages/guardian-prover-health-check-ui/**"
  pull_request:
    paths:
      - "packages/guardian-prover-health-check-ui/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/guardians-ui-ci.yml

  # Deployment name follow the pattern: deploy_<appname(guardian-prover-health-check-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_guardians-ui_hekla_preview:
    if: ${{ github.ref_name != 'main' }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
          environment: 'preview'
          flags: ''
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_UI_HEKLA }}

  deploy_guardians-ui_devnet_preview:
    if: ${{ github.ref_name != 'main' }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
          environment: 'preview'
          flags: ''
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_UI_INTERNAL }}

  deploy_guardians-ui_hekla_production:
    if: ${{ github.ref_name == 'main' && contains(github.ref, 'refs/tags/guardians-ui-') }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: 'production'
      flags: '--prod'
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_UI_HEKLA }}
