name: Optaiko

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/optaiko/**"
    branches-ignore:
      - release-please--branches--**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: ${{ github.event.pull_request.draft == false && !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'dependabot') }}
    runs-on: [arc-runner-set]
    permissions:
      contents: write
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Fetch owner/repo of pull request
        uses: alessbell/pull-request-comment-branch@v2.1.0
        id: comment-branch

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
          fetch-depth: 0
          token: ${{ github.event.pull_request.head.repo.fork == false && secrets.TAIKO_KITTY_TOKEN || github.token }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.5.0
        with:
          version: nightly

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Prepare generated artifacts directories for CI
        working-directory: ./packages/optaiko
        run: |
          mkdir -p contracts
          git ls-files 'contracts/**/*_Layout.sol' | xargs -r git update-index --no-skip-worktree || true
          git config merge.ours.driver true

      - name: Clean and format
        if: github.event.pull_request.head.repo.fork == false
        working-directory: ./packages/optaiko
        run: pnpm clean && pnpm fmt:sol

      - name: Run tests
        working-directory: ./packages/optaiko
        run: pnpm test

      - name: Generate storage layout
        working-directory: ./packages/optaiko
        run: pnpm layout

      - name: Check for changes
        id: git_status
        run: |
          git add -N .
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit generated artifacts
        if: steps.git_status.outputs.changes == 'true' && github.event.pull_request.head.repo.fork == false
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update optaiko generated artifacts"
          branch: ${{ github.head_ref }}
          push_options: "--force-with-lease"
