name: Protocol

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/protocol/**"
      - "!packages/protocol/contract_layout_*"
      - "!packages/protocol/audit/**"
      - "!packages/protocol/docs/**"
      - "!packages/protocol/simulation/**"
      - "!packages/protocol/deployments/**"
      - "!packages/protocol/script/layer2/hekla/**"
      - "!packages/protocol/script/layer2/mainnet/**"
      - "!packages/protocol/script/layer1/hekla/**"
      - "!packages/protocol/script/layer1/mainnet/**"
      - "!packages/protocol/script/layer1/preconf/**"
      - "!packages/protocol/script/layer1/provers/**"
      - "!packages/protocol/script/layer1/team/**"
    branches-ignore:
      - release-please--branches--**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-protocol:
    if: ${{ github.event.pull_request.draft == false  && !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'dependabot') }}
    runs-on: [arc-runner-set]
    permissions:
      # Give the necessary permissions for stefanzweifel/git-auto-commit-action.
      contents: write
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Prepare environment
        continue-on-error: true
        run: sudo apt-get update && sudo apt-get install -y git wget

      - name: Fetch owner/repo of pull request
        uses: alessbell/pull-request-comment-branch@v2.1.0
        id: comment-branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # account for forked repos case
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
          # Fetch more history for better git operations
          fetch-depth: 0
          token: ${{ github.event.pull_request.head.repo.fork == false && secrets.TAIKO_KITTY_TOKEN || github.token }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.4.0
        with:
          version: stable

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Clean up and fmt
        if: github.event.pull_request.head.repo.fork == false
        working-directory: ./packages/protocol
        run: pnpm clean && forge fmt

      - name: Shared-Unit tests
        working-directory: ./packages/protocol
        run: pnpm compile:shared && pnpm test:shared && pnpm layout:shared

      - name: L2-Unit tests
        working-directory: ./packages/protocol
        run: pnpm compile:shared && pnpm compile:l2 && pnpm test:l2 && pnpm layout:l2

      - name: L1-Unit tests
        working-directory: ./packages/protocol
        run: pnpm compile:shared && pnpm compile:l1 && pnpm snapshot:l1 && pnpm layout:l1

      - name: Check for changes
        id: git_status
        run: |
          git add -N .  # Simulate staging to detect untracked files
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit contract layout table
        if: env.changes == 'true' && github.event.pull_request.head.repo.fork == false
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "forge fmt & update contract layout tables"
          branch: ${{ github.head_ref }}
          push_options: "--force-with-lease"

      - name: L1-Deploy contracts
        working-directory: ./packages/protocol
        timeout-minutes: 4
        run: |
          anvil &
          until cast chain-id --rpc-url "http://localhost:8545" 2> /dev/null; do
            sleep 1
          done
          pnpm test:deploy:l1

  genesis-docker:
    if: ${{ github.event.pull_request.draft == false  && !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'dependabot') }}
    runs-on: [taiko-runner]
    permissions:
      # Give the necessary permissions for stefanzweifel/git-auto-commit-action.
      contents: write
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Compile
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm compile

      - name: L2-Generate Genesis (using docker)
        working-directory: ./packages/protocol
        run: pnpm genesis:test
