name: Protocol

on:
  push:
    branches: [main]
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: protocol - Unit Tests (foundry)
        run: forge test -vvv --gas-report > gasreport.ansi
        env:
          # make fuzzing semi-deterministic to avoid noisy gas cost estimation
          # due to non-deterministic fuzzing (but still use pseudo-random fuzzing seeds)
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}

      - name: Compare gas reports
        uses: Rubilmax/foundry-gas-diff@v3.13
        with:
          report: gasreport.ansi
          ignore: test/**/*,lib/**/*
          header: |
            # Taiko gas diffs
        id: gas_diff

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.gas_diff.outputs.markdown }}
          delete: ${{ !steps.gas_diff.outputs.markdown }}

      - name: protocol - Run snapshot (foundry)
        run: forge snapshot

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: protocol - Unit Tests (hardhat)
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm test

      - name: protocol - Integration Tests (hardhat)
        working-directory: ./packages/protocol
        run: pnpm test:integration

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact gas costs
          delete: ${{ !steps.gas_diff.outputs.markdown }}
          message: ${{ steps.gas_diff.outputs.markdown }}

      - name: protocol - Bridge Tests (hardhat)
        working-directory: ./packages/protocol
        run: pnpm test:bridge

      - name: protocol - Test Coverage (hardhat)
        working-directory: ./packages/protocol
        run: pnpm test:coverage

      - name: protocol - Generate Genesis (hardhat)
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      - name: protocol - Export ABIs
        working-directory: ./packages/protocol
        run: pnpm export:abi

      - name: protocol - Deploy L1 Contracts
        working-directory: ./packages/protocol
        run: |
          anvil &
          while ! nc -z localhost 8545; do
            sleep 1
          done
          pnpm deploy:foundry

      - name: protocol - Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/protocol/coverage
          flags: protocol

  post-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up protocol
        uses: ./.github/actions/set-up-protocol

      - name: Run the command to update the documentation
        run: pnpm -F protocol export:docs

      - name: Stage all modified and untracked files
        run: git add .

      - name: Exit if there are no changes
        run: git diff --exit-code --cached

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "docs(protocol): auto-update protocol documentation"
          commit-message: "docs(protocol): auto-update protocol documentation"
          branch: update-docs-${{ github.sha }}
          delete-branch: true
