name: Protocol

on:
  push:
    branches: [main]
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build:
    runs-on: [taiko-runner]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2cb875799419c907cc3709e586ece2559e6b340e

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Check formatting
        working-directory: ./packages/protocol
        run: forge fmt --check

      - name: Unit Tests
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm test

      - name: Generate Genesis
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      # TODO: CompilerError: Stack too deep
      # - name: Test Coverage
      #   working-directory: ./packages/protocol
      #   run: pnpm test:coverage

      - name: Run snapshot (foundry)
        working-directory: ./packages/protocol
        run: pnpm snapshot

      - name: Deploy L1 Contracts
        working-directory: ./packages/protocol
        run: |
          anvil --hardfork cancun &
          while ! nc -z localhost 8545; do
            sleep 1
          done
          pnpm test:deploy

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     directory: ./packages/protocol/coverage
      #     flags: protocol
