name: Protocol

on:
  push:
    branches: [main]
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build-protocol:
    runs-on: [taiko-runner]
    permissions:
      # Give the necessary permissions for stefanzweifel/git-auto-commit-action.
      contents: write
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Unit tests
        working-directory: ./packages/protocol
        run: pnpm clean && forge fmt && pnpm test:l1 && pnpm layout:l1 && pnpm test:l2 && pnpm layout:l2

      - name: Commit contract layout table
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "forge fmt & update contract layout tables"

      - name: Generate genesis
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      - name: Deploy L1 contracts
        working-directory: ./packages/protocol
        run: |
          anvil --hardfork cancun &
          while ! nc -z localhost 8545; do
            sleep 1
          done
          pnpm test:deploy:l1
