name: Merge Gatekeeper

on:
  pull_request:
    types: [synchronize, opened, reopened, edited, ready_for_review]
  merge_group: # Trigger in merge queue to pass the required status check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge-gatekeeper:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    runs-on: [arc-runner-set]
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          timeout: 1800
          interval: 60
          token: ${{ secrets.GITHUB_TOKEN }}
