name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
  merge_group: # Trigger in merge queue to pass the required status check

jobs:
  merge-gatekeeper:
    if: github.event_name == 'pull_request'
    runs-on: [taiko-runner]
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          timeout: 1200
          token: ${{ secrets.GITHUB_TOKEN }}
