name: Vercel Build and Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      flags:
        type: string
        required: true
    secrets:
      vercel_project_id:
        description: "Vercel Project ID"
        required: true
      vercel_org_id:
        description: "Vercel ORG ID"
        required: true
      vercel_token:
        description: "Vercel TOKEN"
        required: true

env:
  VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
  VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}

jobs:
  build-deploy:
    runs-on: [taiko-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.vercel_token }}

      - name: Build Project Artifacts
        run: vercel build ${{ inputs.flags }} --token=${{ secrets.vercel_token }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt ${{ inputs.flags }} --token=${{ secrets.vercel_token }}
