name: "Taiko Client Hive Tests"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/taiko-client/**"
      - "go.mod"
      - "go.sum"
    branches-ignore:
      - release-please--branches--**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hive_tests:
    if: ${{ github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'option.hive-test') }}
    name: hive tests
    runs-on: [arc-runner-set]
    timeout-minutes: 40

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Clone taikoxyz/hive
        run: git clone https://github.com/taikoxyz/hive.git /tmp/hive

      - name: Hive tests
        working-directory: packages/taiko-client
        run: |
          export HIVE_DIR=/tmp/hive
          go test -v -p=1 ./integration_test -timeout=2400s
