name: "Taiko Client Preconf Blocks Documentation"

on:
  push:
    branches: [main]
    paths:
      - "packages/taiko-client/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-and-deploy:
    runs-on: [arc-runner-set]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install swaggo
        run: |
          export CGO_ENABLED=0
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger documentation
        run: |
          export CGO_ENABLED=0
          cd packages/taiko-client
          ./scripts/gen_swagger_json.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/taiko-client/docs # Set this to where your `index.html` is located
          publish_branch: gh-pages
          destination_dir: preconf_blocks_api
