name: Whitepaper
on:
  push:
    branches: [main]
    paths:
      - "packages/whitepaper/**"
  pull_request:
    paths:
      - "packages/whitepaper/**"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.15"

      - name: Compile main.tex
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./packages/whitepaper
          root_file: main.tex

      - name: Rename
        working-directory: ./packages/whitepaper
        run:  rm -rf build/ && mkdir build && mv main.pdf build/taiko-whitepaper.pdf

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/whitepaper/build
